### PR TITLE
Fix tests to work with alcotest 1.1.0 

### PR DESCRIPTION
**Pull request by lippirk**

### CODE REVIEW

**Comment by psafont** [comment]
Travis fails due to the alcotest_lwt breaking change:
```
- dune build @install --profile release
Processing  1/2: [xapi-nbd: dune runtest]
+ /home/opam/.opam/4.08/bin/dune "runtest" (CWD=/home/opam/.opam/4.08/.opam-switch/build/xapi-nbd.master)
- File "lib_test/suite.ml", line 39, characters 25-41:
- 39 | let () = Lwt_main.run @@ Alcotest_lwt.run "suite" [("Vbd_store", test_set)]
-                               ^^^^^^^^^^^^^^^^
- Error: Unbound value Alcotest_lwt.run
```
until alcotest_lwt 1.1.0 is not available on xs-opam the tests will keep failing to build

**Review by lindig — APPROVED** [review]

**Review by psafont — APPROVED** [review]
Tested successfully on a local switch with alcotest 1.1.0
